Repository IntersectMBO/cardano-addresses, pull requests merged in 2020-09, with the labels that each got.

#65 Completely disable RDRAND in cryptonite using a cabal flag
  cabal.project
  stack.yaml
Labels: PR:IMPROVING CODE

#66 infer bech32 prefix from base address for pointer & delegation
  command-line/lib/Command/Address/Delegation.hs
  command-line/lib/Command/Address/Pointer.hs
  command-line/test/Command/Address/DelegationSpec.hs
  command-line/test/Command/Address/PointerSpec.hs
  core/lib/Cardano/Address/Style/Shelley.hs
Labels: PR:RESOLVING ISSUE

#75 Derivation of multisig keys
  core/lib/Cardano/Address/Derivation.hs
  core/lib/Cardano/Address/Style/Byron.hs
  core/lib/Cardano/Address/Style/Icarus.hs
  core/lib/Cardano/Address/Style/Jormungandr.hs
  core/lib/Cardano/Address/Style/Shelley.hs
  core/test/Cardano/Address/Style/IcarusSpec.hs
  core/test/Cardano/Address/Style/JormungandrSpec.hs
  core/test/Cardano/Address/Style/ShelleySpec.hs
  core/test/Test/Arbitrary.hs
Labels: PR:ADDING FEATURE

#77 turn back script hashes as 28 bytes.
  command-line/lib/Command/Address/Bootstrap.hs
  command-line/test/Command/Address/InspectSpec.hs
  core/lib/Cardano/Address/Style/Shelley.hs
  schemas/address-inspect.json
Labels: PR:RESOLVING ISSUE
